apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microshop-ingress
spec:
  rules:
  - host: microshop.local
    http:
      paths:
      - path: /orders
        pathType: Prefix
        backend:
          service:
            name: apigateway
            port:
              number: 80
